version: "2.0"

services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: 5.6
    networks:
      - backend
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: 2.4.32
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    container_name: apache
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "dbtest"
      MYSQL_USER: "otherUser"
      MYSQL_PASSWORD: "password"
    container_name: mysql  
      
networks:
  frontend:
  backend:
